function [ v0, t ] = get_v0( vf, s0, s, n, d, m, g )
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here
    
    syms t

    assume(t>0);
    v = sym('v', [3, 1]);
    [vx, vy, vz, t] = solve( ...
        (m*v(1) + 3*pi*d*n*s0(1))/(3*pi*d*n) - ...
     (m*v(1)*exp(-(3*pi*d*n*t)/m))/(3*pi*d*n) == s(1), ...
    (m*v(2) + 3*pi*d*n*s0(2))/(3*pi*d*n) - ...
     (m*v(2)*exp(-(3*pi*d*n*t)/m))/(3*pi*d*n) == s(2), ...
    (3*pi*d*n*(m*v(3) + 3*pi*d*n*s0(3)) - g*m^2 + ...
     3*pi*d*g*m*n*t)/(9*pi^2*d^2*n^2) + (exp(-(3*pi*d*n*t)/m)* ...
     (g*m^2 - 3*pi*d*n*v(3)*m))/(9*pi^2*d^2*n^2) == s(3), ...
     sqrt((v(1)*exp(-(3*pi*d*n*t)/m))^2 +  ...
     (v(2)*exp(-(3*pi*d*n*t)/m))^2 + ...
     ((exp(-(3*pi*d*n*t)/m)*(g*m^2 + 3*pi*d*n*v(3)*m))/ ...
    (3*pi*d*m*n) - (g*m)/(3*pi*d*n))^2) == vf, v(1), v(2), v(3), t ...     
 );
    
v0 = double([vx; vy; vz]);
t = double(t);

end

